import PDFDocument from "pdfkit";

export const generatePDFReport = (res, filename, reportTitle, summary, headers, rows, totalKeys = [], userName = "System Admin", filtersApplied = {}) => {
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.setHeader("Content-Type", "application/pdf");

  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape",
    margins: { top: 40, left: 40, right: 40, bottom: 40 },
    bufferPages: true
  });

  doc.pipe(res);

  const primaryColor = "#1B365D"; // TransitOps Dark Navy
  const secondaryColor = "#4A5568";
  const lightBgColor = "#F7FAFC";
  const borderColor = "#E2E8F0";

  // --- HEADER BLOCK ---
  // Draw Logo Box Placeholder
  doc.rect(40, 40, 50, 50).fill(primaryColor);
  doc.fillColor("#FFFFFF").fontSize(18).font("Helvetica-Bold").text("TO", 40, 56, { width: 50, align: "center" });

  // TransitOps Title
  doc.fillColor(primaryColor).fontSize(20).font("Helvetica-Bold").text("TransitOps Fleet Management", 105, 42);
  doc.fillColor(secondaryColor).fontSize(13).font("Helvetica").text(reportTitle, 105, 65);

  // Metadata block (Right side)
  const rightAlignX = doc.page.width - 240;
  doc.fillColor(secondaryColor).fontSize(9).font("Helvetica-Bold").text(`Generated Date:`, rightAlignX, 42, { continued: true });
  doc.font("Helvetica").text(` ${new Date().toISOString().split("T")[0]}`);
  doc.font("Helvetica-Bold").text(`Generated By:`, rightAlignX, 54, { continued: true });
  doc.font("Helvetica").text(` ${userName}`);
  doc.font("Helvetica-Bold").text(`Filters:`, rightAlignX, 66, { continued: true });
  
  const filterList = [];
  if (filtersApplied.from) filterList.push(`From: ${filtersApplied.from}`);
  if (filtersApplied.to) filterList.push(`To: ${filtersApplied.to}`);
  if (filtersApplied.vehicleId) filterList.push(`Vehicle: ${filtersApplied.vehicleId.substring(0,8)}`);
  if (filtersApplied.driverId) filterList.push(`Driver: ${filtersApplied.driverId.substring(0,8)}`);
  if (filtersApplied.tripStatus) filterList.push(`TripStatus: ${filtersApplied.tripStatus}`);
  if (filtersApplied.expenseType) filterList.push(`ExpenseType: ${filtersApplied.expenseType}`);
  if (filtersApplied.fuelType) filterList.push(`FuelType: ${filtersApplied.fuelType}`);
  if (filtersApplied.maintenanceStatus) filterList.push(`MntStatus: ${filtersApplied.maintenanceStatus}`);
  
  const filterText = filterList.length > 0 ? filterList.join(", ") : "None";
  doc.font("Helvetica").text(` ${filterText}`, { width: 200 });

  // Draw separator line
  doc.moveTo(40, 105).lineTo(doc.page.width - 40, 105).strokeColor(borderColor).lineWidth(1).stroke();

  // --- SUMMARY KPI CARDS ---
  let yPos = 120;
  if (summary && Object.keys(summary).length > 0) {
    doc.fillColor(primaryColor).fontSize(12).font("Helvetica-Bold").text("Summary Metrics", 40, yPos);
    yPos += 18;

    const cardsKeys = Object.keys(summary).slice(0, 5); // display up to 5 metrics
    const cardWidth = (doc.page.width - 80 - (cardsKeys.length - 1) * 10) / cardsKeys.length;

    cardsKeys.forEach((key, i) => {
      const cardX = 40 + i * (cardWidth + 10);
      doc.rect(cardX, yPos, cardWidth, 45).fill(lightBgColor);
      doc.rect(cardX, yPos, cardWidth, 45).strokeColor(borderColor).stroke();

      const formattedLabel = key.replace(/([A-Z])/g, " $1").replace(/^./, str => str.toUpperCase());
      doc.fillColor(secondaryColor).fontSize(7).font("Helvetica-Bold").text(formattedLabel, cardX + 5, yPos + 8, { width: cardWidth - 10, align: "center" });

      let val = summary[key];
      if (typeof val === "number" && !Number.isInteger(val)) val = val.toFixed(2);
      doc.fillColor(primaryColor).fontSize(13).font("Helvetica-Bold").text(String(val), cardX + 5, yPos + 22, { width: cardWidth - 10, align: "center" });
    });

    yPos += 60;
  }

  // --- DATA TABLE ---
  doc.fillColor(primaryColor).fontSize(12).font("Helvetica-Bold").text("Details Table", 40, yPos);
  yPos += 18;

  const tableWidth = doc.page.width - 80;
  const colWidth = tableWidth / headers.length;

  // Render Table Header
  doc.rect(40, yPos, tableWidth, 20).fill(primaryColor);
  doc.fillColor("#FFFFFF").fontSize(8).font("Helvetica-Bold");
  headers.forEach((h, i) => {
    doc.text(h.label, 45 + i * colWidth, yPos + 6, { width: colWidth - 10, align: "left" });
  });
  yPos += 20;

  // Render Rows
  doc.fontSize(7).font("Helvetica");
  rows.forEach((row, rowIndex) => {
    // Check page overflow
    if (yPos > doc.page.height - 70) {
      doc.addPage();
      yPos = 40;
      // Re-draw headers on new page
      doc.rect(40, yPos, tableWidth, 20).fill(primaryColor);
      doc.fillColor("#FFFFFF").fontSize(8).font("Helvetica-Bold");
      headers.forEach((h, i) => {
        doc.text(h.label, 45 + i * colWidth, yPos + 6, { width: colWidth - 10, align: "left" });
      });
      yPos += 20;
      doc.fontSize(7).font("Helvetica");
    }

    // Alternating background
    if (rowIndex % 2 === 1) {
      doc.rect(40, yPos, tableWidth, 18).fill(lightBgColor);
    }
    // Draw row bottom line
    doc.moveTo(40, yPos + 18).lineTo(40 + tableWidth, yPos + 18).strokeColor(borderColor).lineWidth(0.5).stroke();

    doc.fillColor(secondaryColor);
    headers.forEach((h, i) => {
      let val = row[h.key];
      if (val instanceof Date) val = val.toISOString().split("T")[0];
      if (val === null || val === undefined) val = "";
      
      doc.text(String(val), 45 + i * colWidth, yPos + 5, { width: colWidth - 10, align: "left" });
    });

    yPos += 18;
  });

  // Grand Totals Row
  if (totalKeys.length > 0) {
    if (yPos > doc.page.height - 70) {
      doc.addPage();
      yPos = 40;
    }
    doc.rect(40, yPos, tableWidth, 20).fill(lightBgColor);
    doc.moveTo(40, yPos).lineTo(40 + tableWidth, yPos).strokeColor(primaryColor).lineWidth(1).stroke();
    doc.moveTo(40, yPos + 20).lineTo(40 + tableWidth, yPos + 20).strokeColor(primaryColor).lineWidth(1).stroke();

    doc.fillColor(primaryColor).font("Helvetica-Bold");
    headers.forEach((h, i) => {
      if (i === 0) {
        doc.text("Grand Total", 45, yPos + 6, { width: colWidth - 10 });
      } else if (totalKeys.includes(h.key)) {
        let sum = 0;
        for (const r of rows) {
          sum += Number(r[h.key] || 0);
        }
        doc.text(sum.toFixed(2), 45 + i * colWidth, yPos + 6, { width: colWidth - 10 });
      }
    });
    yPos += 20;
  }

  // Draw Page Numbers in Footer
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fillColor(secondaryColor).fontSize(8).font("Helvetica");
    doc.text(
      `Page ${i + 1} of ${range.count}`,
      40,
      doc.page.height - 30,
      { align: "center", width: doc.page.width - 80 }
    );
  }

  doc.end();
};
